name: Trigger Vercel Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel Webhook
        run: curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}"
